const ResearchTypes = {
	START_SELECT_RESEARCH: 'START_SELECT_RESEARCH',
	SUCCESS_SELECT_RESEARCH: 'SUCCESS_SELECT_RESEARCH',
	FAIL_SELECT_RESEARCH: 'FAIL_SELECT_RESEARCH',
}

export default ResearchTypes