const quotationTypes = {
	START_POST_QUOTATION: 'START_POST_QUOTATION',
	SUCCESS_POST_QUOTATION: 'SUCCESS_POST_QUOTATION',
	FAIL_POST_QUOTATION: 'FAIL_POST_QUOTATION',
}

export default quotationTypes